    return {
        // -------- Aliases en espanol (shape interno historico)
        slugUrl,
        serviceId,
        serviceType,
        sku,
        linkFases: allowCombine ? linkedPhases : null,
        permitirCombinar: allowCombine,
        tiempoFase1: phase1Duration,
        tiempoExposicion: exposureDuration,
        tiempoFase2: phase2Duration,
        duracionTotal: totalDuration,
        buffer,
        staffDisponible,
        staffOptions,
        categoryId,
        categoryName,
        locationId,
        localizacion,
        internalNotes,
        depositAmount,
        depositType,
        onlinePayment,
        inPersonPayment,
        taxIncluded,
        taxRate,
        pricingModel,
        currency,

        // -------- Aliases en ingles (contratos de bookingSaga.js y otros)
        linkedPhases: allowCombine ? linkedPhases : null,
        allowCombine: allowCombine,
        phase1Duration,
        exposureDuration,
        phase2Duration,
        totalDuration,
        hidden: isHiddenF2,

        // -------- Metadata agregada
        metadata: {
            titulo: title,
            tituloServicio: title,
            precio: price,
            duracionTotal: estimatedTotal,
            localizacion,
            resumenCorto,
            descripcionLarga,
            pricingModel,
            addons,
            addonsPrecio: addons.map((addon) => Number(addon?.precio || 0)),
            imageUrl,
            currency,
            taxRate,
            pricing: { base: price, currency },
            timing: { estimatedTotal, totalDuration: estimatedTotal },
        },
    };
